# Docker compose file for Redis + Python REST service example
version: '3'
services:
  api_automation:
    image: fbarquero/api-automation-python
    volumes:
      - ./results:/tmp/results
    # If adding a fixed container name then won't be able to scale
    container_name: ui-auto