# Docker image for flask service

# FROM python:2.7-alpine
FROM ubuntu:18.04
RUN apt-get update && apt-get upgrade -y
RUN apt-get install python-pip -y
RUN mkdir /tmp/results
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
# CMD ["nosetests", "-v", "--with-xunit", "--xunit-file=/tmp/results/test_result.xml"]
# CMD ["cat", "/app/tests/test_python_selenium.py"]
WORKDIR /app
CMD ["nosetests"]